### ISSUE TITLE
Fix grammar issues in README.mb 

### ISSUE THREAD

**Issue by KaevonD** [Warzone/mars#20]
There are a few grammar mistakes throughout the README.md

**Comment by Mew2K** [comment]
As of right now, I do not see any grammar errors within the README.md. There are a few UK spellings, so perhaps those were the specific “grammar mistakes” you thought were present, unless there were some other mistakes that got fixed by now.

Either way, this issue should probably be closed, as again, there does not appear to be any grammar errors as of the latest version of the README.md.

**Comment by KaevonD** [comment]
@Mew2K ah I fixed these issues a while ago, I must have forgotten to close this issue
